### ISSUE TITLE
Admin Password

### ISSUE THREAD

**Issue by Faizaankhan3** [chotumotu11/growcart#2]
Admin Password not working as per the db seed

**Comment by chotumotu11** [comment]
Works completely fine. Unable to replicate the problem. Until further steps for replication is provided I am closing the issue. 
Thanks

**Comment by Faizaankhan3** [comment]
WAsn't working for Heroku ;)

**Comment by chotumotu11** [comment]
growcart on Heroku Admin password has been changed due to security and monetary reasons.

**Comment by Faizaankhan3** [comment]
I see.
